### ISSUE TITLE
Project repository for Louis

### ISSUE THREAD

**Issue by LOHankins** [ga-dc/wdi9-project2-gallery#7]
https://github.com/LOHankins/Project-2.git

**Comment by tylercrosse** [comment]
What you have for the MVP is great and sounds like a fantastic set of things to focus on. I think flushing those out and creating some more targeted user stories for those things would really help you reel in the scope. Your ERD is super complicated which is a great thing to strive for but shouldn't be the focus right off the bat. The same thing goes with your current user stories, an admin feature is doable but potentially tricky to implement and probably isn't required to give you app some basic functionality. Based on the ERD it seems like contact info is really a User model since it is used to link to other tables. I really encourage you to keep it super simple to start and then build on it instead of getting everything working at once.
